version: '3'

services:
  frontend:
    build:
      context: ./
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nsa.rule=Host(`nsa.kiltonpisli.me`)"
      - "traefik.http.routers.nsa.entrypoints=web"
    network_mode: bridge
    restart: always

