version: '3'
name: nsa-prod

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nsa.rule=Host(`nsa.kiltonpisli.me`)"
      - "traefik.http.routers.nsa.entrypoints=web"
    network_mode: bridge
    restart: always

# docker compose up -d