name: Gatsby Publish

on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
      - run : npm install && npm run build
      - uses: actions/deploy-pages@v2
      
          
