name: Gatsby Deploy

on:
  push:
    branches: master


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false



jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: gatsby
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3
        run: npm run deploy:ci
