name: Deploy Gatsby Site

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Gatsby
        run: npm install 
      - name: Build Gatsby Site
        run: npm run build
      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          publish-branch: gh-pages
          directory: public
